### ISSUE TITLE
Some issues using this buildpack

### ISSUE THREAD

**Issue by axelson** [chrismcg/heroku-buildpack-elixir-mix-release#1]
Hi, first off thanks for creating this buildpack! As I am using heroku-buildpack-phoenix-static it sems that I need to use this.

However I'm running into some problems.

The `bin/detect` script is failing because I don't have a `rel` directory in the root of my repository. But I wouldn't expect to have one there anyway, if anything I'd expect to have `_build/rel`, but that would only be there if the release was already built in a different buildpack (and I'd rather just build the release once). Shouldn't `bin/detect` basically look identical to https://github.com/HashNuke/heroku-buildpack-elixir/blob/a0fd1ce618761c745a8c3d6fe2bb6ba1fb220906/bin/detect ?

I'm also getting this error:
```
remote: Elixir Mix Release script compile running
remote: ** (RuntimeError) environment variable SECRET_KEY_BASE is missing.
```

So imported the `export_env_vars` function which fixes that. But now I'm having trouble with phoenix binding to the incorrect port which is probably related to configuration again, although perhaps it's just normal release configuration issues.

So my question is if you've seen these same issues and should I push up a PR that fixes some of them?

**Comment by chrismcg** [comment]
Hi @axelson! The `rel` folder is created by `mix release.init` so that's why bin/detect is checking for that. It has some template files that are used by the release process so the buildpack assumes that if it's not there then the app isn't setup for mix releases. (See https://github.com/chrismcg/phlink/tree/master/rel for an example).

I can access the `SECRET_KEY_BASE` env variable without needing to import `export_env_vars` in the app I use this in. It's been a while since I set it up and it was upgraded from distillery so it's possible that I missed a step or have some legacy config that happens to make things work. I'll have a look into it sometime this week to see if I can reproduce.

**Comment by axelson** [comment]
I realized that I should have prefaced my issue to say that this is my first time trying out releases (didn't use distillery before).

From what I can tell in the documentation it looks like running `mix release.init` is not required: https://hexdocs.pm/mix/Mix.Tasks.Release.html And is only first mentioned in https://hexdocs.pm/mix/Mix.Tasks.Release.html#module-vm-args-and-env-sh-env-bat where it says:
> Developers may want to customize the VM flags and environment variables given when the release starts. This is typically done by customizing two files inside your release: releases/RELEASE_VSN/vm.args and releases/RELEASE_VSN/env.sh (or env.bat on Windows).
>
> However, instead of modifying those files after the release is built, the simplest way to customize those files is by running `mix release.init`

So I think that a change to the `bin/detect` script should be made.

It also looks like the snippet that the elixir buildpack uses for exporting config vars during the compile step is heavily based on a snippet from the Heroku docs:
https://devcenter.heroku.com/articles/buildpack-api#bin-compile

But the good news is that I got it working!

Application repo: https://github.com/axelson/makeup_live_format
Buildpack repo: https://github.com/axelson/heroku-buildpack-elixir-mix-release
Deployed url: https://makeup-live-format.herokuapp.com/

**Comment by chrismcg** [comment]
Ah ok, I must have ran `mix release.init` to see what it did and then assumed it was normal. I agree that the `bin/detect` script should be updated to just check for Elixir. I'm happy to have a look at what you did and make the changes but I'm not sure when I'll get around to it. If you want to send a PR that'd be grand too but no worries if you haven't the time.

**Comment by chrismcg** [comment]
@axelson can you look over #2 and try it out? Worked fine for my simple example app but would like a second opinion :) It's copied from your fork so just want to make sure I didn't miss anything important.

**Comment by axelson** [comment]
Okay, I'll try it out. Thanks!
